//
// Created by ztk on 2021-06-13.
//

#ifndef SAUERKRAUT_PARTICLES_H
#define SAUERKRAUT_PARTICLES_H

namespace kraut::engine::particles {
    enum
    {
        PART_BLOOD = 0,
        PART_WATER,
        PART_SMOKE,
        PART_STEAM,
        PART_FLAME,
        PART_FIREBALL1, PART_FIREBALL2, PART_FIREBALL3,
        PART_STREAK, PART_LIGHTNING,
        PART_EXPLOSION, PART_EXPLOSION_BLUE,
        PART_SPARK, PART_EDIT,
        PART_SNOW,
        PART_MUZZLE_FLASH1, PART_MUZZLE_FLASH2, PART_MUZZLE_FLASH3,
        PART_HUD_ICON,
        PART_HUD_ICON_GREY,
        PART_TEXT,
        PART_TEXT_ICON,
        PART_METER, PART_METER_VS,
        PART_LENS_FLARE
    };
}

#endif //SAUERKRAUT_PARTICLES_H
